module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌹', '💕', '💞', '😍', '🥰', '☺️', '🙂', '😇', '🌟', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BwWffeDwiqe6cjDDklYJ5m?mode=ems_copy_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/kunzpz.png',
    NEWSLETTER_JID: '120363419140572186@newsletter',
    NEWSLETTER_MESSAGE_ID: '5775',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'BILAL-MD MINI',
    OWNER_NAME: 'BILAL',
    OWNER_NUMBER: '923078071982',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '*👑 MINI BOT 👑*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vaj3Xnu17EmtDxTNnQ0G'
};
